### ISSUE TITLE
gradle cant find textsurface

### ISSUE THREAD

**Issue by j2emanue** [elevenetc/TextSurface#2]
compile 'com.github.elevenetc:textsurface:0.9.0'  cannot be found even after i add the maven repo.  can you check ?

**Comment by elevenetc** [comment]
Did you add `jitpack.io` to `repositories` block?

**Comment by j2emanue** [comment]
i had to put repositories {
    maven { url "https://jitpack.io" }
} into the apps build.gradle file. I had it at the top level where jcenter is declared and it wasn't working there. So i moved it to module's gradle file and then it works. But its too bad i need api 15 or above. i wanted backward compatibility. you can close this issue.

**Comment by elevenetc** [comment]
The library works with `minSdkVersion 15`. See `build.gradle` of the sample: https://github.com/elevenetc/TextSurface/blob/master/app/build.gradle

**Comment by j2emanue** [comment]
i wanted minsdkVersion to be 9
