### ISSUE TITLE
Its not working with proguard build

### ISSUE THREAD

**Issue by j2emanue** [elevenetc/TextSurface#4]
i put this in my proguard build to try and help but it did not help:

-keepclasseswithmembernames class xsu.levenetc.android.textsurface.*\* {
}

what im experiencing is not a failure but rather the animation wont run on release builds.

**Comment by elevenetc** [comment]
Sorry for the delay. Thanks for pointing out the problem! I'll try to fix this within next the 24hrs.

**Comment by elevenetc** [comment]
You need to add this to your `proguard-rules` file:

```
-keep class su.levenetc.android.textsurface.** { *; }
```
